project:
  type: website
  output-dir: docs
  # output-dir: TEMP

website:
  site-url: "https://johanvantent.github.io/meerdoenmetdata"
  favicon: "images/JTIP.png"
  title: "Meer doen met data"
  page-navigation: true
  navbar:
    logo: "images/JTIP_grey80.png"
    logo-alt: "Inverse Pi"
    left:
      - text: "Blog"
        icon: pencil
        file: blog.qmd
      - text: "Boeken"
        icon: book
        file: boeken.qmd
      - text: "R-packages"
        icon: box
        file: packages.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/RedTent
  twitter-card:
    creator: "@inversepi"
    title: "Meer doen met data"
    description: "Over data, visualisatie, programmeren in R en waterkwaliteit"
  open-graph:
    locale: nl_NL
    site-name: "Meer doen met data"
      
  
format:
  html:
    theme: 
      light: [sandstone, styles-light.scss]
      dark: slate
    css: styles.css

lang: nl

execute: 
  freeze: auto

twitter-card: true
