project:
  type: website
  output-dir: docs

website:
  favicon: "images/JTIP.png"
  title: "Meer doen met data"
  page-navigation: true
  navbar:
    logo: "images/JTIP_grey80.png"
    logo-alt: "Inverse Pi"
    left:
      - text: "Blog"
        icon: pencil
        file: blog.qmd
      - text: "Boeken"
        icon: book
        file: boeken.qmd
      - text: "R-packages"
        icon: box
        file: packages.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/RedTent
  
format:
  html:
    theme: 
      light: [sandstone, styles-light.scss]
      dark: slate
    css: styles.css


execute: 
  freeze: auto

