---
title: "Boeken"
editor: visual
---

Lijst van interessante (gelezen) boeken en andere resources. Veel van de onderstaande boeken en resources zijn (ook) online te lezen.

-   Big book of R
-   Rework podcast
-   diverse boeken (KAhneman, How we learn etc.)

------------------------------------------------------------------------

::: panel-tabset
## Programmeren in R

-   **Mastering Software Development in R** - Roger Peng - *2017*
    -   Bij de bijbehorende cursus op Coursera. De cursus is gratis te volgen, maar voor een certificaat betaal je enkele tientjes.
    -   <https://bookdown.org/rdpeng/RProgDA/>
-   **R for Data Science (R4DS)** - Hadley Wickham - *2019*
    -   Goede introductie in de tidyverse en gebruik van R in het algemeen
    -   <https://r4ds.had.co.nz>
-   **Mastering Shiny** - Hadley Wickham - *2020*
    -   <https://mastering-shiny.org/>
    -   under construction
-   **Tidyverse design guide** - Tidyverse Team - *2019*
    -   Principes voor het ontwerpen packages/software
    -   <https://design.tidyverse.org/>
-   **The tidyverse style guide**
    -   Uitgangspunten om overzichtelijk en consistent te scripten.
    -   <https://style.tidyverse.org>
-   **Efficient R-programming** - Colin Gillespie - *2020*
    -   <https://bookdown.org/csgillespie/efficientR/>
-   **Geocomputation with R** - Robin Lovelace - *2020*
    -   Erg nuttig als je met geo-data in R werkt.
    -   <https://geocompr.robinlovelace.net/>
-   **R Markdown Cookbook** - *2021*
    -   Een schat aan tips en trucs voor het werken met R Markdown
    -   <https://bookdown.org/yihui/rmarkdown-cookbook/>
-   **R packages** - Hadley Wickham, Jenny Bryan - *2021*
    -   Tweede editie <https://r-pkgs.org/> (under construction)
    -   Eerste editie <http://r-pkgs.had.co.nz/>
-   **Advanced R** - Hadley Wickham - *2021*
    -   *The book is designed primarily for R users who want to improve their programming skills and understanding of the language.*
    -   <https://adv-r.hadley.nz/>
-   Happy Git and GitHub for the useR - Jenny Bryan
    -   Nuttig als je met Git of GitHub aan de slag gaat.
    -   <https://happygitwithr.com/>
-   Hands on programming with R - Garett Grolemund
    -   *"I wrote it for non-programmers to provide a friendly introduction to the R language. - Garret Grolemund"*
    -   <https://rstudio-education.github.io/hopr/>
-   R Markdown: The Definitive Guide - Yihui Xie, J.J. Allaire, Garrett Grolemund
    -   Uitgebreide handleiding voor R Markdown
    -   <https://bookdown.org/yihui/rmarkdown/>
-   bookdown: Authoring Books and Technical Documents with R Markdown - Yihui Xie
    -   *"This short book introduces an R package, bookdown, to change your workflow of writing books."*
    -   <https://bookdown.org/yihui/bookdown/>
-   Statistical Inference via Data Science: A ModernDive into R and the Tidyverse - Chester Ismay and Albert Y. Kim
    -   *"Help! I'm new to R and RStudio and I need to learn them! What do I do?" If you're asking yourself this, this book is for you.*
    -   <https://moderndive.com/>
-   R Graphics Cookbook, 2nd edition - Winston Chang
    -   *"a practical guide that provides more than 150 recipes to help you generate high-quality graphs quickly"*
    -   <https://r-graphics.org/>
-   ggplot2: elegant graphics for data analysis - Hadley Wickham, Danielle Navarro, and Thomas Lin Pedersen
    -   *"it's primary focus is explaining the Grammar of Graphics that ggplot2 uses, and describing the full details."*
    -   <https://ggplot2-book.org>

------------------------------------------------------------------------

## Data-analyse

-   **An Introduction to Statistical Learning with Applications in R** - Gareth James, Daniela Witten, Trevor Hastie and Robert Tibshirani - *2018*
    -   Introductie in allerlei methodes voor *Statistical learning* (Machine learning)
    -   <http://faculty.marshall.usc.edu/gareth-james/ISL/>
    -   Zie ook de bijbehorende gratis cursus op de Stanford pagina <https://lagunita.stanford.edu/courses/HumanitiesSciences/StatLearning/Winter2016/about>
-   **Forecasting: Principles and Practice** - Rob J. Hyndman, George Athanasopoulos - *2020*
    -   Analyse en voorspellen van tijdreeksen
    -   <https://otexts.com/fpp3/>
    -   Zie ook: <https://github.com/rstudio-conf-2020/time-series-forecasting>
-   **Head First Data Analysis** - Michael Milton - *2021*
    -   Goede introductie als je nog weinig weet over data-analyse.
    -   Boek leest makkelijk weg en heeft interactieve opzet.
-   Elements of Statistical Learning - Hastie, Tibshirani and Friedman (2009)
    -   <https://web.stanford.edu/~hastie/ElemStatLearn/>
-   Applied Predictive Modeling - Max Kuhn, Kjell Johnson
    -   Praktische toepassing van voorspelling
    -   Op basis van R.
-   Interpretable Machine Learning - Christoph Molnar
    -   Over hoe je voorkomt dat machine learning alleen een black-box is.
    -   <https://christophm.github.io/interpretable-ml-book/>
-   Supervised Machine Learning for Text Analysis in R - Emil Hvitfeldt and Julia Silge
    -   <https://smltar.com/>
-   Tidy Modeling with R - Max Kuhn and Julia Silge
    -   <https://www.tmwr.org/>
-   Feature Engineering and Selection: A Practical Approach for Predictive Models - Max Kuhn and Kjell Johnson
    -   <https://bookdown.org/max/FES/>

------------------------------------------------------------------------

## Data Visualisatie

-   **Storytelling with Data** - Cole Nussbaumer Knaflic - *2019*
    -   Hoe gebruik je grafieken om een duidelijke boodschap over te brengen
    -   <http://www.storytellingwithdata.com/books>
-   **The visual display of quantitative information** - Edward Tufte - *2020*
    -   Klassieker over het weergeven van data in grafieken.
    -   <https://www.edwardtufte.com/tufte/books_vdqi>
-   **Show Me the Numbers** - Stephen Few - *2020*
    -   Gedetailleerde uitleg over het ontwerp van tabellen en grafieken
    -   <http://www.stephen-few.com/smtn.php>
-   **Signal** - Stephen Few - *2020*
    -   Over het onderscheiden van signaal en ruis
    -   Veel overlap met andere boeken en de aanpak is beperkt toepasbaar
-   **Info We Trust** - R.J. Andrews - *2020*
    -   Meer filosofisch ingestoken boek over data-visualisatie
-   **The Functional Art** - Alberto Cairo - *2020*
    -   Benadert het vanuit een journalistiek perspectief.
    -   Veel aandacht voor infographics
-   **The Big Book of Dashboards** - Steve Wexler, Jeffrey Shaffer, Andy Cotgreave - *2020*
    -   Grote hoeveelheid voorbeelden van dashboards voor uiteenlopende situaties
-   **Information Visualization - Perception for Design** - Colin Ware - *2021*
    -   Boek dat diep in gaat op visueel waarnemen en hoe dat leidt tot perceptie. Deze kennis wordt vervolgens vertaald in praktische richtlijnen voor het creëren van visualisaties.
-   Fundamentals of Data Visualization - Claus O. Wilke
    -   <https://serialmentor.com/dataviz/>
-   Visual Thinking for Design - Colin Ware

------------------------------------------------------------------------

## Overig

-   **The Sense of Structure** - George D. Gopen - *2018*
    -   Erg nuttig om te begrijpen hoe je als schrijver de juiste boodschap overbrengt aan je lezers. George Gopen doet dit aan de hand van de Reader Expectation Approach. Het helpt om erachter te komen wat een lezer verwacht en hoe je die kennis als schrijver kunt gebruiken.
    -   Veel van de principes worden ook uitgelegd in the Litigation Articles <https://www.georgegopen.com/the-litigation-articles.html>
-   **The design of everyday things** - Don Norman - *2017*
    -   Over ontwerpen: hoe maak je iets dat goed functioneert, dat voldoet aan de wensen van de gebruikers.
-   **An introduction to APIs** - Brian Cooksey - *2019*
    -   Over hoe APIs werken
    -   <https://zapier.com/learn/apis/>
-   **The Creative Curve** - Allen Gannett - *2020*
    -   How to Develop the Right Idea, at the Right Time
-   **How design makes the world** - Scott Berkun - *2020*
    -   Overzichtelijk en goed leesbaar boek dat een overzicht geeft wat "design" is en hoe dat in de praktijk werkt.
-   **Design Thinking** - Nigel Cross - *2021*
    -   Hoe werken en denken designers?
    -   Boek met diverse voorbeelden en studies die illustreren hoe designers denken.
-   **Badass - Making Users Awesome** - Kathy Sierra - *2021*
    -   Geweldig boek dat veel inzicht geeft je mensen kunt leren om ergens goed in te worden.
    -   Veel inzichten over hoe mensen en de automatische processen werken en hoe je dat kunt benutten om ze iets te leren.

------------------------------------------------------------------------

## Tutorials

-   Tidymodels - Get Started
    -   <https://www.tidymodels.org/start/>

------------------------------------------------------------------------

## Podcasts

-   *Not So Standard Deviations* - Roger Peng & Hilary Parker
    -   Not So Standard Deviations: The Data Science Podcast Roger Peng and Hilary Parker talk about the latest in data science and data analysis in academia and industry.
    -   <http://nssdeviations.com/>
-   *Storytelling with Data Podcast* - Cole Nussbaumer Knaflic
    -   Rid your world of ineffective graphs and mediocre presentations, one exploding 3D pie chart at a time! The storytelling with data podcast covers topics related to data storytelling, better presentations, and all things data viz. There is a story in your data---get the skills and power to tell it!
    -   <http://www.storytellingwithdata.com/podcast>

------------------------------------------------------------------------

## Video's

-   **Plotting anything with ggplot2** - Thomas Lin Pedersen - *2020*
    -   Uitgebreide workshop over hoe ggplot2 werkt
    -   Deel 1: <https://www.youtube.com/watch?v=h29g21z0a68> (2,5 uur)
    -   Deel 2: <https://www.youtube.com/watch?v=0m4yywqNPVY> (2 uur)

------------------------------------------------------------------------

## Blogs

-   *Creating Passionate Users* - Kathy Sierra
    -   <https://headrush.typepad.com/>
        -   [Too many companies are like bad marriages](https://headrush.typepad.com/creating_passionate_users/2007/02/too_many_compan.html)
        -   [What tail is wagging the "user happiness" dog?](https://headrush.typepad.com/creating_passionate_users/2007/02/what_tail_is_wa.html)
        -   [Don't ask employees to be passionate about the company!](https://headrush.typepad.com/creating_passionate_users/2007/02/dont_ask_employ.html)
-   **Serious Pony** - Kathy Sierra
    -   <http://seriouspony.com/blog>
    -   Twee geweldige artikelen over presenteren en over 'cognitive load'

------------------------------------------------------------------------

## Wensenlijst

-   #MakeoverMonday - Andy Kriebel, Eva Murray
-   Information Dashboard design - Stephen Few
-   Style: Lessons in Clarity and Grace - Joseph Williams Joseph Bizup

------------------------------------------------------------------------
:::

#### Toelichting

**Vet** betekent geheel gelezen

*Cursief* betekent gedeeltelijk gelezen
